name: Unit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  release:
    name: Unit Tests
    runs-on: ubuntu-latest
    # Don't run job when commit is made by semantic release
    if: "!contains(github.event.head_commit.message, 'semantic-release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit
        env:
          DEV_ID: ${{ secrets.DEV_ID }}
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
